### ISSUE TITLE
xlsm: rows not splitted correctly

### ISSUE THREAD

**Issue by brunoqc** [tafia/office#2]
```
| 1 | a |
| 2 | b |
| 3 | c |
```

output
```
0,0: Int(1)
0,1: String("a")
1,0: String("b")
1,1: Int(3)
row: [Int(1), String("a"), Int(2)]
row: [String("b"), Int(3), String("c")]
```

code
```rust
extern crate office;
use office::Excel;

fn main() {
    let mut excel = Excel::open("test.xlsm").unwrap();
    let r = excel.worksheet_range("Feuil1").unwrap();
    println!("0,0: {:?}", r.get_value(0, 0));
    println!("0,1: {:?}", r.get_value(0, 1));
    println!("1,0: {:?}", r.get_value(1, 0));
    println!("1,1: {:?}", r.get_value(1, 1));

    for row in r.rows() {
        println!("row: {:?}", row);
    }   
}
```

**Comment by tafia** [comment]
I didn't know someone else was using this repo!

Thanks for the issue I'll have a look asap

**Comment by tafia** [comment]
I couldn't find time to work on it until today. I believe #4 fixes both or your issues. 

I'd really appreciate if you can confirm (for instance I only have a english version of Excel and while I believe the behavior is the same with a French one, I'd like a confirmation).
Thanks

**Comment by brunoqc** [comment]
It's weird, you just commented here 5 mins ago but I replied to the PR 26 mins ago.

**Comment by tafia** [comment]
Yeah, didn't see your answer. Anyway thanks again for the issues. Once I'll find some time to work on readme/documentation + some big missing part I'll probably publish it. Also not really fan of the same, do you have some idea?
