### ISSUE TITLE
can't parse a float if the excel's format is numeric without precision

### ISSUE THREAD

**Issue by brunoqc** [tafia/office#5]
I have a '0.5' value. In Excel I see '1'. The cells' format seems to be set to numeric with 0 precision digits.

**Comment by tafia** [comment]
I don't really understand the issue. Om my test it is outputting `Float(0.5)`, isn't what you'd expect?
Else would you mind providing an excel file I could test (open a pr with a broken test)?

**Comment by brunoqc** [comment]
I tested with a xlsx file. With 0.5 in A1 and B1 and I don't have the problem.
row: [Float(0.5), Float(0.5)].

I tested with a file that I had the problem with before and I don't have the problem. I also tested with an older office's commit.

Maybe I had some modifications in lib.rs.
