### ISSUE TITLE
error "not v node" when the cell is a formula

### ISSUE THREAD

**Issue by brunoqc** [tafia/office#6]
formula: CONCAT("a", "b")

**Comment by tafia** [comment]
Well unfortunately formula are not implemented yet (the error is not really helping either, I'll change this).
It is not a small task and I'm not sure I can do this in a short time. 

Do you want to try implementing a basic support? At least basic functions like: 
- arithmetic operations, 
- concat
- find
- vlookup/hlookup
- string functions (left, right, mid)

**Comment by brunoqc** [comment]
I think there's a way to get the current value without having to interpret the formula. I'm able to read it with 2bbcb08c415451029af621a0abe777d5ebe2f378 but I'm not sure it's the best way

Maybe the better way would be to ignore when `e.name() == b"f"` and add a case in https://github.com/tafia/office/blob/c0cc6e7f94d3a1c7bf637c6f2f72e0a771b7e4d9/src/lib.rs#L325 when `k == b"r"` (I think) but I'm not sure what the attributes' values means on this cell (there's 3 of them, not 1 like https://github.com/tafia/office/blob/c0cc6e7f94d3a1c7bf637c6f2f72e0a771b7e4d9/src/lib.rs#L328).

**Comment by tafia** [comment]
I agree with you skipping the `<f>` node might be better for now.

Here is what I have:
```xml
<c r="A3" t="str">
<f>CONCATENATE("a","b")</f>
<v>ab</v>
</c>
```

And for a regular `=A1<A2` formula
```xml
<c r="A4" t="b">
<f>A1&gt;A2</f>
<v>0</v>
</c>
```

I am not an expert on excel either, I assume (I'll check that properly later) 
- `t=str` means regular string (that cannot be shared because it is a result of a formula)
- `t=b` means boolean

Updating the code accordingly in #7.

**Comment by brunoqc** [comment]
oh it's b"str". I'm an idiot. For some reason I though [115, 116, 114] meant multiple attributes. Didn't realize it spelled "str" haha.
