### ISSUE TITLE
Clean the project and publish to crates.io

### ISSUE THREAD

**Issue by tafia** [tafia/office#8]
Out of my mind:
- [x] license
- [ ] better readme (a status about xlsb and xls management out of vba) (#20)
- [x] documentation (will then probably rely on doc.rs
- [ ] more tests
- [x] travis and appveyor badges
- [x] clippy (#18)
- [ ] rustfmt (#21)
- [x] use stable toolchain per default (#15 #19)

**Comment by brunoqc** [comment]
Maybe also add a travis and appveyor badges.

**Comment by brunoqc** [comment]
Add maybe also run [rustfmt](https://github.com/rust-lang-nursery/rustfmt) and maybe use https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server to ensure the style is always good.

**Comment by tafia** [comment]
closing this one in favor of individual issues with milestones

**Comment by tafia** [comment]
cc @brunoqc 
https://crates.io/crates/office

I am waiting for docs.rs to build the docs, then update the readme and I'll make a post on reddit.
Thanks again for the issues you reported, your pr, your patience and your suggestions!

**Comment by brunoqc** [comment]
> https://crates.io/crates/office

Nice!

> I'll make a post on reddit

Maybe you could also post on the [What’s everyone working on this week](https://users.rust-lang.org/t/what-s-everyone-working-on-this-week-44-2016/7857) thread.

> Thanks again for the issues you reported, your pr, your patience and your suggestions!

Thanks also to you for your quick replies and quick fixes.
